### ISSUE TITLE
Support for writing String to Database

### ISSUE THREAD

**Issue by Redirts** [DrBarnabus/secure-pass#2]
When I attempt to convert the buff toString it will create a String with kind of padding at the end that stops me from inserting it into a Postgres database.

**Comment by alexdrans** [comment]
You can encode the buffer as a base64 string

```javascript
const getSecurePassword = async (str) => {
  const sp = new SecurePass();
  const password = Buffer.from(str);
  const res = await sp.hashPassword(password);
  return res.toString('base64')
}

const verifyPassword = async (storedPassword, providedPassword) => {
  const sp = new SecurePass();
  const prov = Buffer.from(providedPassword);
  const stored = Buffer.from(storedPassword, 'base64');
  const result = await sp.verifyHash(prov, stored);
  if (SecurePass.isInvalidOrUnrecognized(result)) { 
    console.log('Hash not created by SecurePass or invalid');
  } else if (SecurePass.isInvalid(result)) {
    console.log('Password not valid when compared with supplied hash');
  } else if (SecurePass.isValid(result)) {
    console.log('Password and Hash are a match');
  } else if (SecurePass.isValidNeedsRehash(result)) {
    console.log('Password and Hash are a match, but the security of the hash could be improved by rehashing.');
  }
}
```

**Comment by DrBarnabus** [comment]
Sorry for the late Reply. But as @alexdrans suggested converting to base64 is the best solution.

The padding is there because the length of the buffers used by the underlying implementation is very specific and I needed to maintain this throughout to keep it consistent.

You can use `bufferFromSafeBase64` and `bufferToSafeBase64` which are exported by the library to convert them. There is documentation for these functions here: https://drbarnabus.github.io/secure-pass/globals.html#bufferfromsafebase64
